---
# Common settings for all nodes
app_user: "{{ ansible_user }}"
app_group: "{{ ansible_user }}"
app_base_dir: /opt/ipd
project_src: "{{ playbook_dir }}/../project"

# Versions
go_version: "1.22.5"
go_download_url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
python_version: "3.12"

# Paths
go_install_dir: /usr/local/go
venv_dir: "{{ app_base_dir }}/venv"
